kind: Pod
apiVersion: v1
metadata:
  name: pod-nginx-iscsi
spec:
  containers:
    - name: nginx-iscsi
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: canbeanything
  volumes:
    - name: canbeanything
      iscsi:
        targetPortal: 10.0.207.103:3260
        iqn: iqn.1992-08.com.netapp:sn.23d61586bcd111e68ccb0800274617cf:vs.4
        lun: 0
        fsType: 'ext4'
        readOnly: false

