kind: Pod
apiVersion: v1
metadata:
    name: pod-nginx-iscsi
spec:
  containers:
      - name: nginx-iscsi
        image: nginx
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: canbeanything
  volumes:
      - name: canbeanything
        iscsi:
          targetPortal: 10.0.207.103:3260
          iqn: iqn.1992-08.com.netapp:sn.36d2ef9089ac11e6b624080027e5941d:vs.4
          lun: 0 
          fsType: 'ext4'
          readOnly: false


