kind: Pod
apiVersion: v1
metadata:
  name: pod-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: nginx-vol
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: pvc-20mb

