kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1gb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 10.63.171.153:3260 
    iqn: iqn.2010-01.com.solidfire:xe7v.maestro-vol1-gold.45 
    lun: 0
    fsType: 'ext4'
    readOnly: false
