kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv20mb
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.207.101  
    path: "/vol_20mb_file"
