kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv20mb
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 10.0.207.103:3260
    iqn: iqn.1992-08.com.netapp:sn.6849b192a50311e6a44108002726d095:vs.4
    lun: 0
    fsType: 'ext4'
    readOnly: false
